# Generated by Django 2.2.6 on 2019-12-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='price',
            field=models.IntegerField(default=300),
            preserve_default=False,
        ),
    ]
